import type { DesignSystem } from '@/types/design'

export function exportAsCSS(s: DesignSystem): string {
  return `/* Cliq System — Design System */
:root {
  /* Neutrals */
  --background: ${s.neutrals.background};
  --foreground: ${s.neutrals.foreground};
  --surface: ${s.neutrals.surface};

  /* Brand */
  --primary: ${s.palette.primary};
  --secondary: ${s.palette.secondary};
  --tertiary: ${s.palette.tertiary};

  /* Typography */
  --font-display: '${s.typography.displayFont}', sans-serif;
  --font-heading: '${s.typography.headingFont}', sans-serif;
  --font-body: '${s.typography.bodyFont}', sans-serif;
  --font-size-base: ${s.typography.fontSize}px;
  --font-weight-body: ${s.typography.bodyWeight};
  --text-casing: ${s.typography.casing};

  /* UI Style */
  --radius: ${s.uiStyle.radius}px;
  --shadow: 0 4px 12px rgba(0,0,0,${s.uiStyle.shadowIntensity / 1000});
  --border-width: ${s.uiStyle.borderWidth}px;
  --spacing-scale: ${s.uiStyle.spacingScale};

  /* Layout */
  --navbar-height: ${s.layout.navbarHeight}px;
  --section-padding: ${s.layout.sectionPadding}px;
  --hero-padding: ${s.layout.heroPadding}px;
  --grid-gap: ${s.layout.gridGap}px;

  /* Components */
  --card-radius: ${s.components.card.radius}px;
  --card-padding: ${s.components.card.padding}px;
  --modal-radius: ${s.components.modal.radius}px;
  --modal-max-width: ${s.components.modal.maxWidth}px;
}

body {
  background-color: var(--background);
  color: var(--foreground);
  font-family: var(--font-body);
  font-size: var(--font-size-base);
}

h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); }
.font-display { font-family: var(--font-display); }
`
}

export function exportAsTailwindConfig(s: DesignSystem): string {
  return `// tailwind.config.js (v3) — generated by Cliq System
module.exports = {
  theme: {
    extend: {
      colors: {
        background: '${s.neutrals.background}',
        foreground: '${s.neutrals.foreground}',
        surface: '${s.neutrals.surface}',
        primary: '${s.palette.primary}',
        secondary: '${s.palette.secondary}',
        tertiary: '${s.palette.tertiary}',
      },
      fontFamily: {
        display: ['${s.typography.displayFont}', 'sans-serif'],
        heading: ['${s.typography.headingFont}', 'sans-serif'],
        body: ['${s.typography.bodyFont}', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '${s.uiStyle.radius}px',
      },
    },
  },
}

/* Tailwind v4 alternative — paste into your globals.css:

@theme {
  --color-background: ${s.neutrals.background};
  --color-foreground: ${s.neutrals.foreground};
  --color-surface: ${s.neutrals.surface};
  --color-primary: ${s.palette.primary};
  --color-secondary: ${s.palette.secondary};
  --color-tertiary: ${s.palette.tertiary};
  --font-display: '${s.typography.displayFont}', sans-serif;
  --font-heading: '${s.typography.headingFont}', sans-serif;
  --font-body: '${s.typography.bodyFont}', sans-serif;
  --radius: ${s.uiStyle.radius}px;
}
*/
`
}

export function exportAsJSONTokens(s: DesignSystem): string {
  const tokens = {
    color: {
      background: { value: s.neutrals.background },
      foreground: { value: s.neutrals.foreground },
      surface: { value: s.neutrals.surface },
      primary: { value: s.palette.primary },
      secondary: { value: s.palette.secondary },
      tertiary: { value: s.palette.tertiary },
    },
    font: {
      display: { value: s.typography.displayFont },
      heading: { value: s.typography.headingFont },
      body: { value: s.typography.bodyFont },
    },
    size: {
      base: { value: `${s.typography.fontSize}px` },
      radius: { value: `${s.uiStyle.radius}px` },
      'border-width': { value: `${s.uiStyle.borderWidth}px` },
    },
    layout: {
      'navbar-height': { value: `${s.layout.navbarHeight}px` },
      'section-padding': { value: `${s.layout.sectionPadding}px` },
      'hero-padding': { value: `${s.layout.heroPadding}px` },
      'grid-gap': { value: `${s.layout.gridGap}px` },
    },
  }
  return JSON.stringify(tokens, null, 2)
}

export function exportAsMarkdown(s: DesignSystem): string {
  return `# Design System Tokens

## Colors

| Token | Value |
|-------|-------|
| Background | \`${s.neutrals.background}\` |
| Foreground | \`${s.neutrals.foreground}\` |
| Surface | \`${s.neutrals.surface}\` |
| Primary | \`${s.palette.primary}\` |
| Secondary | \`${s.palette.secondary}\` |
| Tertiary | \`${s.palette.tertiary}\` |

## Typography

| Token | Value |
|-------|-------|
| Display Font | ${s.typography.displayFont} |
| Heading Font | ${s.typography.headingFont} |
| Body Font | ${s.typography.bodyFont} |
| Base Size | ${s.typography.fontSize}px |
| Body Weight | ${s.typography.bodyWeight} |
| Casing | ${s.typography.casing} |

## UI Style

| Token | Value |
|-------|-------|
| Border Radius | ${s.uiStyle.radius}px |
| Shadow Intensity | ${s.uiStyle.shadowIntensity} |
| Border Width | ${s.uiStyle.borderWidth}px |
| Spacing Scale | ${s.uiStyle.spacingScale}× |

## Layout

| Token | Value |
|-------|-------|
| Navbar Height | ${s.layout.navbarHeight}px |
| Section Padding | ${s.layout.sectionPadding}px |
| Hero Padding | ${s.layout.heroPadding}px |
| Grid Gap | ${s.layout.gridGap}px |

## Color Ratio

\`${s.ratio.join(' / ')}\`

## Theme

${s.theme}

## Icons

Provider: ${s.icons.provider}
`
}

export function exportAsHTMLTemplate(s: DesignSystem): string {
  const css = exportAsCSS(s)
  return `<!DOCTYPE html>
<html lang="en"${s.theme === 'dark' ? ' class="dark"' : ''}>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your Design System</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(s.typography.displayFont)}:wght@400;600;700;800&family=${encodeURIComponent(s.typography.headingFont)}:wght@400;600;700&family=${encodeURIComponent(s.typography.bodyFont)}:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
${css}

* { box-sizing: border-box; margin: 0; padding: 0; }
.container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }

/* Navbar */
.navbar {
  height: var(--navbar-height);
  background: var(--surface);
  border-bottom: var(--border-width) solid rgba(0,0,0,0.08);
  display: flex; align-items: center; justify-content: space-between;
  padding: 0 24px;
}
.logo { font-family: var(--font-display); font-weight: 700; font-size: 20px; }
.nav-links { display: flex; gap: 24px; align-items: center; }
.nav-links a { color: var(--foreground); text-decoration: none; opacity: 0.7; }

/* Buttons */
.btn-primary {
  background: var(--primary); color: #fff;
  padding: 10px 20px; border-radius: var(--radius); border: 0;
  font-weight: 600; cursor: pointer; box-shadow: var(--shadow);
}
.btn-secondary {
  background: transparent; color: var(--foreground);
  padding: 10px 20px; border-radius: var(--radius);
  border: var(--border-width) solid currentColor; font-weight: 600; cursor: pointer;
}

/* Hero */
.hero {
  padding: var(--hero-padding) 24px;
  text-align: center;
}
.hero h1 {
  font-family: var(--font-display);
  font-size: 56px; font-weight: 800; line-height: 1.1;
  margin-bottom: 16px;
}
.hero p { font-size: 18px; opacity: 0.7; max-width: 640px; margin: 0 auto 32px; }
.hero-cta { display: flex; gap: 12px; justify-content: center; }

/* Features */
.features { padding: var(--section-padding) 24px; background: var(--surface); }
.features h2 {
  font-family: var(--font-heading); font-size: 36px; font-weight: 700;
  text-align: center; margin-bottom: 48px;
}
.feature-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: var(--grid-gap);
}
.card {
  background: var(--background);
  border-radius: var(--card-radius);
  padding: var(--card-padding);
  box-shadow: var(--shadow);
  border: var(--border-width) solid rgba(0,0,0,0.06);
}
.card h3 { font-family: var(--font-heading); font-size: 20px; margin-bottom: 8px; }
.card p { opacity: 0.7; }

/* Footer */
.footer { padding: 48px 24px; text-align: center; opacity: 0.6; font-size: 14px; }
</style>
</head>
<body>
  <nav class="navbar">
    <div class="logo">Your Brand</div>
    <div class="nav-links">
      <a href="#">Features</a>
      <a href="#">Pricing</a>
      <a href="#">About</a>
      <button class="btn-primary">Get Started</button>
    </div>
  </nav>

  <section class="hero">
    <h1>Beautiful design,<br>built for you.</h1>
    <p>This page was generated from your Cliq System design system. Every color, spacing, and font is yours.</p>
    <div class="hero-cta">
      <button class="btn-primary">Start Free</button>
      <button class="btn-secondary">Learn More</button>
    </div>
  </section>

  <section class="features">
    <h2>Features</h2>
    <div class="feature-grid">
      <div class="card"><h3>Fast</h3><p>Lightning-quick performance for the modern web.</p></div>
      <div class="card"><h3>Accessible</h3><p>WCAG-compliant by default, every color combination tested.</p></div>
      <div class="card"><h3>Customizable</h3><p>Every token in your hands, ready to tweak.</p></div>
    </div>
  </section>

  <footer class="footer">© ${new Date().getFullYear()} Your Brand · Generated with Cliq System</footer>
</body>
</html>
`
}

export function downloadFile(content: string, filename: string, mime = 'text/plain') {
  if (typeof window === 'undefined') return
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function copyToClipboard(text: string): Promise<void> {
  if (typeof navigator !== 'undefined' && navigator.clipboard) {
    return navigator.clipboard.writeText(text)
  }
  return Promise.reject(new Error('Clipboard not available'))
}
